export const APP_CONSTANTS = {
  API_PREFIX: '/api/v1',
  MAX_PROFILE_PHOTOS: 6,
  MIN_DATING_AGE: 18,
  MAX_DATING_AGE: 100,
  OTP_EXPIRATION_MINUTES: 5,
  MAX_OTP_ATTEMPTS: 3,
  DEFAULT_DISCOVERY_LIMIT: 20,
  UNVERIFIED_TEASER_LIMIT: 5,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
} as const;
